version: '3.8'

services:
  bot:
    build: .
    environment:
      - NODE_ENV=production
      - BALE_BOT_TOKEN=${BALE_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro